# Example sequences for each designer tool
# Source: human GAPDH (NM_002046) and ACTB (NM_001101) reference sequences

# ── Regular PCR ───────────────────────────────────────────────────────────────
# Human GAPDH partial CDS (~500 bp)
EXAMPLE_REG_PCR = (
    "ATGGGGAAGGTGAAGGTCGGAGTCAACGGATTTGGTCGTATTGGGCGCCTGGTCACCAGG"
    "GCTGCTTTTAACTCTGGTAAAGTGGATATTGTTGCCATCAATGACCCCTTCATTGACCTCA"
    "ACTACATGGTTTACATGTTCCAATATGATTCCACCCATGGCAAATTCCATGGCACCGTCAAG"
    "GCTGAGAACGGGAAGCTTGTCATCAATGGAAATCCCATCACCATCTTCCAGGAGCGAGATC"
    "CCTCCAAAATCAAGTGGGGCGATGCTGGCGCTGAGTACGTCGTGGAGTCCACTGGCGTCTTC"
    "ACCACCATGGAGAAGGCTGGGGCTCATTTGCAGGGGGGAGCCAAAAGGGTCATCATCTCTGC"
    "CCCCTCTGCTGATGCCCCCATGTTCGTCATGGGTGTGAACCATGAGAAGTATGACAACAGCC"
    "TCAAGATCATCAGCAATGCCTCCTGCACCACCAACTGCTTAGCACCCCTGGCCAAGGTCATC"
    "CATGACAACTTTGGTATCGTGGAAGG"
)

# ── qPCR — Junction-spanning ──────────────────────────────────────────────────
# Human GAPDH exon 8 | exon 9 junction (^ marks the splice site)
EXAMPLE_QPCR_JUNCTION = (
    "TGCACCACCAACTGCTTAGCACCCCTGGCCAAGGTCATCCATGACAACTTTGGTATCGTGG"
    "AAGGACTCATGACCACAGTCCATGCCATCACTGCCACCCAGAAGACTGTGGATGGCCCCTCC"
    "GGGAAACTGTGGCGTGATGGCCGCGGGGCTCTCCAGAACATCATCCCTGCCTCTACTGGCGC"
    "TGCCAAGGCTGTGGGCAAGGTCATCCCTGAGCTGAACGGGAAGCTCACTGGCATGGCCTTCC"
    "GTGTCCCCACTGCCAACGTGTCAGTGGTGGACCTGACCTGCC"
    "^"
    "GTCTAGAAAAACCTGCCAAATATGATGACATCAAGAAGGTGGTGAAGCAGGCGTCGGAGGGC"
    "CCCCTCAAGGGCATCCTGGGCTACACTGAGCACCAGGTGGTCTCCTCTGACTTCAACAGCGA"
    "CACCCACTCCTCCACCTTTGACGCTGGGGCTGGCATTGCCCTCAACGACCACTTTGTCAAGC"
    "TCATTTCCTGGTATGACAACGAATTTGGCTACAGCAACAGGGTGGTGGACCTCATGGCCCAC"
)

# ── qPCR — Intron-flanking ────────────────────────────────────────────────────
# Human ACTB: Exon A (last ~100 bp of exon 5), Exon B (first ~100 bp of exon 6)
EXAMPLE_QPCR_EXON_A = (
    "ATCATGTTTGAGACCTTCAATACCCCCGCCATGTACGTTGCTATCCAGGCTGTGCTATCCC"
    "TGTACGCCTCTGGCCGTACCACTGGCATCGTGATGGACTCCGGTGACGGGGTCACCCACACT"
    "GTGCCCATCTACGAGGGGTATGCCCTCCCCCATGCCATCCTGCGTCTGGACCTGGCTGGCCG"
    "GGACCTGACTGACTACCTCATGAAGATCCTCACCGAGCGCGGCTACAGCTTCACCACCACGG"
)

EXAMPLE_QPCR_EXON_B = (
    "CCGAGCGGGAAATCGTGCGTGACATTAAGGAGAAGCTGTGCTACGTCGCCCTGGACTTCGA"
    "GCAAGAGATGGCCACGGCTGCTTCCAGCTCCTCCCTGGAGAAGAGCTACGAGCTGCCTGACG"
    "GCCAGGTCATCACCATTGGCAATGAGCGGTTCCGCTGCCCTGAGGCACTCTTCCAGCCTTCC"
    "TTCCTGGGCATGGAGTCCTGTGGCATCCACGAAACTACCTTCAACTCCATCATGAAGTGTGA"
)

# ── Splicing ──────────────────────────────────────────────────────────────────
# Human CD44 — Condition 1 (FWD A + FWD B + REV A)
# Exon 1 (const): FWD A binds here
# Exon 8 (variable): FWD B binds here
# Exon 9 (const): REV A binds here
EXAMPLE_SPLICING_FWD_A = (
    "CAAAGACAGCATGGCGCTGCAAATGGATGGCACCCGCTATGTAATCAGCAGTGGCGGCGGC"
    "GGCAGTGGCAATGGCAGTGGCAATGGCAATGCAGCAAATGGCAGCGGCGGTGGCAGCAGCG"
    "GCAGTGGCACCTCAGACAGCATCAATGCTGCAGCAAATGGATGGAGCAGCATGGCAATGGC"
)

EXAMPLE_SPLICING_FWD_B = (
    "ACAGCACCAGCAGTAACAGCAGTAACAGCAGCACCAGTACCAGCACCAGCAATGGCACAGG"
    "CACCAACAATGGTACAAGCAGCACCAGCAGCACCACCAGCATCAGCAGCAGCACCACCAGCA"
    "GCACCACCAGCACCAGCAGCACCAGCAGCAGCAATGGCACCAGCAGCACCAGCAGCACCAGC"
)

EXAMPLE_SPLICING_REV_A = (
    "CTGGGGTGGAATGTGTCTTGGTCTCTGGGTACTCCATGTAATGGTGTCATCAGAGTCACAG"
    "ATGTCAAATGCATTTATGGACAACAGCACCAGCAGCAGTACCAGCAGCAGCAGCAGCAGCAG"
    "CACCTGCAGCAGCAGCACCAGCAGCAGCAGCACCAGCACCAGCAGCAGTACCAGCAGCAGCA"
)
